export enum GlobalEvents {
    SUBMIT_COMPLETE = "FG@SUBMIT_COMPLETE",
    SUBMIT_FAIL = "FG@SUBMIT_FAIL",
    SUBMIT_START = "FG@SUBMIT_START",
    SUBMIT_DONE = "FG@SUBMIT_DONE",

    VALIDATION_FAIL = "FG@VALIDATION_FAIL",

    FROM_RENDERED = "FG@FORM_RENDERED",
    FROM_READY = "FG@FORM_READY",
    FORM_CLEARED = "FG@FORM_CLEARED",

    FORM_NOT_READY_TO_COLLECT = "FG@FORM_NOT_READY_TO_COLLECT",

    VALUE_CHANGED = "FG@VALUE_CHANGED",

    FORM_START_LOADING = "FG@FORM_START_LOADING",
    FORM_END_LOADING = "FG@FROM_END_LOADING"
}

export enum FieldEvents {
    VALIDATION_FAIL = "FIELD_NOT_VALID",
    CHANGE = "FIELD_VALUE_CHANGED",
    CONFIG_CHANGED = "FIELD_CONFIG_CHANGED",
}

